### ISSUE TITLE
witness puzzle solver - solutions with out-of-bounds negative polyominoes not found

### ISSUE THREAD

**Issue by ianh** [jbzdarkid/jbzdarkid.github.io#4]
This puzzle solver tool is really cool! You mentioned in the discord you wanted bug reports; I'm not sure where to file them, so let me know if I should move this somewhere else.

Anyway, here's the bug.  The following puzzle:

```json
{"grid":[[false,false,false,false,false,false,false,false,false],[false,false,false,false,false,false,false,false,false],[false,false,false,false,false,false,false,false,false],[false,{"type":"ylop","color":"blue","polyshape":1,"rot":0},false,{"type":"poly","color":"yellow","polyshape":626,"rot":0},false,{"type":"poly","color":"yellow","polyshape":626,"rot":0},false,{"type":"ylop","color":"blue","polyshape":1,"rot":0},false],[false,false,false,false,false,false,false,false,false],[false,false,false,false,false,false,false,false,false],[false,false,false,false,false,false,false,false,false]],"start":{"x":6,"y":0},"end":{"x":0,"y":8},"dots":[],"gaps":[],"regionCache":{},"pillar":false,"name":"Unnamed Puzzle","valid":0,"negations":[]}
```

ought to have more solutions.  For example, this solution should be valid:

![screen shot 2018-08-12 at 06 42 22](https://user-images.githubusercontent.com/114075/44002648-13ba883a-9dfb-11e8-9fa8-64f66d95da66.png)

It seems like the solver isn't considering the possibility that negative polyominoes could be placed out of bounds.

**Comment by jbzdarkid** [comment]
IIRC the game doesn't allow it either, I'll take a look today.
As far as bug reporting locations go, I prefer this one -- but some people don't have a github account. PMs on discord work too.
