### ISSUE TITLE
Cursor is very slow in Firefox

### ISSUE THREAD

**Issue by vicky5124** [jbzdarkid/jbzdarkid.github.io#8]
The cursor is extremely slow when using a Firefox based browser, to the point where it's unbearable to solve any puzzle. This issue does not present in Chromium browsers. The video demonstrates the issue.

https://github.com/jbzdarkid/jbzdarkid.github.io/assets/8344197/af0f8830-57b4-4379-8530-19507b0a4731

I've noticed that by using inspect element, and increasing the limit of the mouse speed to 5.0, the cursor moves at the same speed as the default value in Chromium, which may serve as a temporary solution while the cursor movement logic is properly fixed for Firefox.

**Comment by jbzdarkid** [comment]
Just curious, what OS are you using? Is this Windows 11?

**Comment by vicky5124** [comment]
This is Arch Linux with the LTS kernel and a Wayland compositor on an AMD GPU with the open source drivers.

**Comment by jbzdarkid** [comment]
I have limited ability to fix this -- WitnessPuzzles is just reacting to what the browser reports for cursor motion.

That said, you should be able to manually change the settings beyond the slider limits -- this will be saved in your per-browser cookies, and should be sticky as long as you don't touch the slider.
`window.settings.sensitivity = 20.0` (or whatever you like)
